name: Build Tomcat

on: [push]

jobs:

  build: 
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: List files
      run: |
           ls -ltr
           java -version
           
    - name: Checkout Tomcat
      uses: actions/checkout@v2
      with: 
        repository: apache/tomcat
        ref: master
        path: ./tomcat
